### ISSUE TITLE
Cannot be replaced with an empty string

### ISSUE THREAD

**Issue by skyline-123** [sawhney17/logseq-find-replace#4]
If the Replace input box is empty and cannot be replaced, I think this verification is a kind of trouble.

**Comment by sawhney17** [comment]
Can you elaborate on this?

**Comment by skyline-123** [comment]
![image](https://user-images.githubusercontent.com/22638687/176212632-bc94647f-ca8a-49f2-93c1-355f7918655b.png)
I wish I could replace ddd with an empty string, but it's not supported right now. The replace all button has a non-null check.

**Comment by sawhney17** [comment]
Perhaps add a space?

**Comment by sawhney17** [comment]
If not, I can add a manual override

**Comment by skyline-123** [comment]
> If not, I can add a manual override

Spaces can indeed achieve this replacement requirement, but this does not feel very consistent with the code editor logic I use every day, such as vscode.

**Comment by sawhney17** [comment]
Should be possible  now
