### ISSUE TITLE
not working in latest version?

### ISSUE THREAD

**Issue by cnut1648** [sawhney17/logseq-find-replace#6]
Hi, thank you for providing this great functionality.
I found that in the latest version (logseq 0.7.9), this plugin seems to be not working.
For example consider this page and I want to replace "most relevant one" (marked in red)
![image](https://user-images.githubusercontent.com/37067883/183003108-7dc2377d-8043-43f8-b436-87d252d1cf5f.png)

I did
![image](https://user-images.githubusercontent.com/37067883/183003069-8833dd98-b234-48da-9cde-f80896ae5446.png)
And click `Replace All.` A success message pop up, but the string is not replaced.

And it seems to throw an error below
![image](https://user-images.githubusercontent.com/37067883/183003305-3a1c22c6-19c9-4f7c-8693-feed6c89f079.png)

I wonder what might cause it. Thanks!

**Comment by sawhney17** [comment]
Should work now!
